apiVersion: v1
kind: Service
metadata:
  name: llm-ops-sandbox-api
  labels:
    app.kubernetes.io/name: llm-ops-sandbox
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: llm-ops-sandbox
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
